# Generated by Django 4.1.7 on 2023-02-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('release', models.DateField(verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название компании')),
                ('type_of_company', models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Региональный дистрибьютер'), (2, 'Розничная сеть'), (3, 'Магазин'), (4, 'Индивидуальный предприниматель')], default=4, verbose_name='Тип контрагента')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задолженность перед поставщиком')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email компании контрагента')),
                ('country', models.CharField(default=None, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(default=None, max_length=100, verbose_name='Город')),
                ('street', models.CharField(default=None, max_length=150, verbose_name='Улица')),
                ('house', models.CharField(default=None, max_length=15, verbose_name='Дом')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('product', models.ManyToManyField(related_name='product', to='network.products', verbose_name='Карточка продукта')),
            ],
            options={
                'verbose_name': 'Название компании',
                'verbose_name_plural': 'Каталог компаний',
                'ordering': ['title'],
            },
        ),
    ]
